# Generated by Django 3.1.5 on 2021-02-02 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('Introduce', models.TextField(max_length=50)),
                ('local', models.CharField(choices=[('063', '전라북도'), ('02', '서울특별시'), ('043', '충청북도'), ('031', '경기도'), ('033', '강원도'), ('064', '제주특별자치도'), ('032', '인천광역시'), ('052', '울산광역시'), ('055', '경상남도'), ('041', '충청남도'), ('044', '세종특별자치시'), ('054', '경상북도'), ('042', '대전광역시'), ('051', '부산광역시'), ('061', '전라남도'), ('062', '광주광역시'), ('053', '대구광역시')], max_length=3)),
                ('lapse', models.IntegerField(choices=[(1, '팀빌딩'), (2, '아이디어 구상'), (3, '기획완료')])),
                ('deadline', models.IntegerField()),
                ('role', models.CharField(choices=[('Planner', '기획자'), ('developer', '개발자'), ('designer', '디자이너')], max_length=10)),
                ('pd', models.IntegerField(choices=[(0, '0'), (2, '2'), (3, '3'), (1, '1'), (5, '5'), (7, '7'), (4, '4'), (6, '6'), (9, '9'), (10, '10'), (8, '8')])),
                ('dev', models.IntegerField(choices=[(0, '0'), (2, '2'), (3, '3'), (1, '1'), (5, '5'), (7, '7'), (4, '4'), (6, '6'), (9, '9'), (10, '10'), (8, '8')])),
                ('designer', models.IntegerField(choices=[(0, '0'), (2, '2'), (3, '3'), (1, '1'), (5, '5'), (7, '7'), (4, '4'), (6, '6'), (9, '9'), (10, '10'), (8, '8')])),
                ('Publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
