# Generated by Django 3.1.5 on 2021-02-13 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='Publisher',
            new_name='publisher',
        ),
        migrations.RemoveField(
            model_name='article',
            name='Introduce',
        ),
        migrations.AddField(
            model_name='article',
            name='introduce',
            field=models.CharField(default='1', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(default=' ', max_length=100),
        ),
    ]
