# Generated by Django 3.1.5 on 2021-02-02 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='role',
        ),
        migrations.AddField(
            model_name='article',
            name='Now_designer',
            field=models.IntegerField(choices=[(9, '9'), (4, '4'), (5, '5'), (10, '10'), (6, '6'), (1, '1'), (2, '2'), (3, '3'), (8, '8'), (7, '7'), (0, '0')], default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='Now_dev',
            field=models.IntegerField(choices=[(9, '9'), (4, '4'), (5, '5'), (10, '10'), (6, '6'), (1, '1'), (2, '2'), (3, '3'), (8, '8'), (7, '7'), (0, '0')], default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='Now_pd',
            field=models.IntegerField(choices=[(9, '9'), (4, '4'), (5, '5'), (10, '10'), (6, '6'), (1, '1'), (2, '2'), (3, '3'), (8, '8'), (7, '7'), (0, '0')], default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='designer',
            field=models.IntegerField(choices=[(9, '9'), (4, '4'), (5, '5'), (10, '10'), (6, '6'), (1, '1'), (2, '2'), (3, '3'), (8, '8'), (7, '7'), (0, '0')]),
        ),
        migrations.AlterField(
            model_name='article',
            name='dev',
            field=models.IntegerField(choices=[(9, '9'), (4, '4'), (5, '5'), (10, '10'), (6, '6'), (1, '1'), (2, '2'), (3, '3'), (8, '8'), (7, '7'), (0, '0')]),
        ),
        migrations.AlterField(
            model_name='article',
            name='lapse',
            field=models.IntegerField(choices=[(1, '팀빌딩'), (3, '기획완료'), (2, '아이디어 구상')]),
        ),
        migrations.AlterField(
            model_name='article',
            name='local',
            field=models.CharField(choices=[('052', '울산광역시'), ('061', '전라남도'), ('054', '경상북도'), ('055', '경상남도'), ('032', '인천광역시'), ('053', '대구광역시'), ('02', '서울특별시'), ('051', '부산광역시'), ('033', '강원도'), ('043', '충청북도'), ('062', '광주광역시'), ('063', '전라북도'), ('042', '대전광역시'), ('041', '충청남도'), ('044', '세종특별자치시'), ('031', '경기도'), ('064', '제주특별자치도')], max_length=3),
        ),
        migrations.AlterField(
            model_name='article',
            name='pd',
            field=models.IntegerField(choices=[(9, '9'), (4, '4'), (5, '5'), (10, '10'), (6, '6'), (1, '1'), (2, '2'), (3, '3'), (8, '8'), (7, '7'), (0, '0')]),
        ),
    ]
