# Generated by Django 3.1.5 on 2021-02-02 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0002_auto_20210202_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='Now_designer',
            field=models.IntegerField(choices=[(8, '8'), (9, '9'), (10, '10'), (5, '5'), (7, '7'), (6, '6'), (0, '0'), (4, '4'), (3, '3'), (2, '2'), (1, '1')], default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='Now_dev',
            field=models.IntegerField(choices=[(8, '8'), (9, '9'), (10, '10'), (5, '5'), (7, '7'), (6, '6'), (0, '0'), (4, '4'), (3, '3'), (2, '2'), (1, '1')], default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='Now_pd',
            field=models.IntegerField(choices=[(8, '8'), (9, '9'), (10, '10'), (5, '5'), (7, '7'), (6, '6'), (0, '0'), (4, '4'), (3, '3'), (2, '2'), (1, '1')], default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='designer',
            field=models.IntegerField(choices=[(8, '8'), (9, '9'), (10, '10'), (5, '5'), (7, '7'), (6, '6'), (0, '0'), (4, '4'), (3, '3'), (2, '2'), (1, '1')]),
        ),
        migrations.AlterField(
            model_name='article',
            name='dev',
            field=models.IntegerField(choices=[(8, '8'), (9, '9'), (10, '10'), (5, '5'), (7, '7'), (6, '6'), (0, '0'), (4, '4'), (3, '3'), (2, '2'), (1, '1')]),
        ),
        migrations.AlterField(
            model_name='article',
            name='local',
            field=models.CharField(choices=[('062', '광주광역시'), ('033', '강원도'), ('054', '경상북도'), ('055', '경상남도'), ('042', '대전광역시'), ('043', '충청북도'), ('061', '전라남도'), ('052', '울산광역시'), ('031', '경기도'), ('063', '전라북도'), ('064', '제주특별자치도'), ('053', '대구광역시'), ('044', '세종특별자치시'), ('032', '인천광역시'), ('041', '충청남도'), ('051', '부산광역시'), ('02', '서울특별시')], max_length=3),
        ),
        migrations.AlterField(
            model_name='article',
            name='pd',
            field=models.IntegerField(choices=[(8, '8'), (9, '9'), (10, '10'), (5, '5'), (7, '7'), (6, '6'), (0, '0'), (4, '4'), (3, '3'), (2, '2'), (1, '1')]),
        ),
    ]
