# Generated by Django 3.1.5 on 2021-02-13 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0002_auto_20210214_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
