# Generated by Django 3.1.5 on 2021-02-02 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0003_auto_20210202_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='Now_designer',
        ),
        migrations.RemoveField(
            model_name='article',
            name='Now_dev',
        ),
        migrations.RemoveField(
            model_name='article',
            name='Now_pd',
        ),
        migrations.AlterField(
            model_name='article',
            name='designer',
            field=models.IntegerField(choices=[(8, '8'), (3, '3'), (10, '10'), (5, '5'), (4, '4'), (0, '0'), (1, '1'), (6, '6'), (2, '2'), (9, '9'), (7, '7')]),
        ),
        migrations.AlterField(
            model_name='article',
            name='dev',
            field=models.IntegerField(choices=[(8, '8'), (3, '3'), (10, '10'), (5, '5'), (4, '4'), (0, '0'), (1, '1'), (6, '6'), (2, '2'), (9, '9'), (7, '7')]),
        ),
        migrations.AlterField(
            model_name='article',
            name='lapse',
            field=models.IntegerField(choices=[(1, '팀빌딩'), (2, '아이디어 구상'), (3, '기획완료')]),
        ),
        migrations.AlterField(
            model_name='article',
            name='local',
            field=models.CharField(choices=[('061', '전라남도'), ('055', '경상남도'), ('043', '충청북도'), ('052', '울산광역시'), ('044', '세종특별자치시'), ('042', '대전광역시'), ('062', '광주광역시'), ('041', '충청남도'), ('032', '인천광역시'), ('02', '서울특별시'), ('031', '경기도'), ('064', '제주특별자치도'), ('063', '전라북도'), ('033', '강원도'), ('054', '경상북도'), ('051', '부산광역시'), ('053', '대구광역시')], max_length=3),
        ),
        migrations.AlterField(
            model_name='article',
            name='pd',
            field=models.IntegerField(choices=[(8, '8'), (3, '3'), (10, '10'), (5, '5'), (4, '4'), (0, '0'), (1, '1'), (6, '6'), (2, '2'), (9, '9'), (7, '7')]),
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('now_pd', models.IntegerField(choices=[(8, '8'), (3, '3'), (10, '10'), (5, '5'), (4, '4'), (0, '0'), (1, '1'), (6, '6'), (2, '2'), (9, '9'), (7, '7')], default=0)),
                ('now_dev', models.IntegerField(choices=[(8, '8'), (3, '3'), (10, '10'), (5, '5'), (4, '4'), (0, '0'), (1, '1'), (6, '6'), (2, '2'), (9, '9'), (7, '7')], default=0)),
                ('now_designer', models.IntegerField(choices=[(8, '8'), (3, '3'), (10, '10'), (5, '5'), (4, '4'), (0, '0'), (1, '1'), (6, '6'), (2, '2'), (9, '9'), (7, '7')], default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TeamMember', to='accountapp.article')),
            ],
        ),
    ]
