# Generated by Django 3.1.5 on 2021-02-16 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applyapp', '0002_auto_20210214_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='comment',
            field=models.TextField(default=None, max_length=200, null=True),
        ),
    ]
