# Generated by Django 3.1.5 on 2021-02-16 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applyapp', '0004_auto_20210216_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='decision',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
