# Generated by Django 3.1.5 on 2021-02-16 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applyapp', '0006_auto_20210216_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='decision',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
