# Generated by Django 3.1.5 on 2021-02-16 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applyapp', '0007_auto_20210216_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='decision',
            field=models.IntegerField(default=1),
        ),
    ]
