# Generated by Django 3.1.5 on 2021-02-16 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applyapp', '0008_auto_20210216_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='decision',
            field=models.CharField(choices=[(1, '결전전'), (2, '수락'), (3, '거절')], default=1, max_length=20),
        ),
    ]
