# Generated by Django 3.1.5 on 2021-02-16 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applyapp', '0010_auto_20210216_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='comment',
            field=models.TextField(blank=True, default='확인 전 입니다.', max_length=200, null=True),
        ),
    ]
