# Generated by Django 3.1.5 on 2021-02-16 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applyapp', '0011_auto_20210216_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='decision',
            field=models.IntegerField(choices=[(1, '결정전'), (2, '수락'), (3, '거절')], default=1),
        ),
    ]
